// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.ShoppingVan;

namespace Persistence.ShoppingVan.Migrations
{
    [DbContext(typeof(ShoppingVanContext))]
    [Migration("20200903103840_AddingAllProductUnitsToShoppingVan")]
    partial class AddingAllProductUnitsToShoppingVan
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.ShoppingVan.AggregatesModel.ShoppingVanAggregate.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ContentCount")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<float>("SellingPrice")
                        .HasColumnType("real");

                    b.Property<string>("VanItemId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("VanItemId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("VanItemId1");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("Domain.ShoppingVanBoundedContext.AggregatesModel.ShoppingVanAggregate.Van", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalItemsCount")
                        .HasColumnType("int");

                    b.Property<float>("TotalPrice")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ShoppingVans");
                });

            modelBuilder.Entity("Domain.ShoppingVanBoundedContext.AggregatesModel.ShoppingVanAggregate.VanItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VanId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("VanId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VanId1");

                    b.ToTable("ShoppingVanItems");
                });

            modelBuilder.Entity("Domain.ShoppingVan.AggregatesModel.ShoppingVanAggregate.Unit", b =>
                {
                    b.HasOne("Domain.ShoppingVanBoundedContext.AggregatesModel.ShoppingVanAggregate.VanItem", "VanItem")
                        .WithMany("Units")
                        .HasForeignKey("VanItemId1");
                });

            modelBuilder.Entity("Domain.ShoppingVanBoundedContext.AggregatesModel.ShoppingVanAggregate.VanItem", b =>
                {
                    b.HasOne("Domain.ShoppingVanBoundedContext.AggregatesModel.ShoppingVanAggregate.Van", "Van")
                        .WithMany("ShoppingVanItems")
                        .HasForeignKey("VanId1");
                });
#pragma warning restore 612, 618
        }
    }
}
